# Generated by Django 5.1.1 on 2024-09-17 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_check_in_alter_booking_check_out'),
        ('rooms', '0003_room_amenities_room_description_room_photo_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
